name: http_api_handler
description: A Flutter package for handling HTTP API requests with ease, including file uploads and downloads.
version: 1.0.0
homepage: https://github.com/anwarsafy/http_api_handler
repository: https://github.com/anwarsafy/http_api_handler
issue_tracker: https://github.com/anwarsafy/http_api_handler/issues

environment:
  sdk: '>=3.5.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.3.0
  file_picker: ^9.0.2
  logger: ^2.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mockito:
  build_runner: